### ISSUE TITLE
Issue running optimize

### ISSUE THREAD

**Issue by ivanfig** [notadamking/RLTrader#30]
(tf_gpu) C:\Users\idf\Documents\python\Bitcoin-Trader-RL>python ./test.py
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    from stable_baselines.common.policies import MlpLnLstmPolicy
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\stable_baselines\__init__.py", line 4, in <module>
    from stable_baselines.ddpg import DDPG
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\stable_baselines\ddpg\__init__.py", line 1, in <module>
    from stable_baselines.ddpg.ddpg import DDPG
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\stable_baselines\ddpg\ddpg.py", line 12, in <module>
    from mpi4py import MPI
ImportError: DLL load failed: The specified procedure could not be found.

(tf_gpu) C:\Users\idf\Documents\python\Bitcoin-Trader-RL>

**Comment by ivanfig** [comment]
Solved it by installing:

https://www.microsoft.com/en-us/download/confirmation.aspx?id=57467

But now I get

(base) C:\Users\idf\Documents\python\Bitcoin-Trader-RL>python ./optimize.py
Traceback (most recent call last):
  File "./optimize.py", line 11, in <module>
    import optuna
ModuleNotFoundError: No module named 'optuna'

(base) C:\Users\idf\Documents\python\Bitcoin-Trader-RL>

**Comment by moxis** [comment]
Be sure to install all the dependencies with
`pip install -r requirements.txt`

**Comment by stefintrim** [comment]
This is a Windows file path issue - it doesn't like the Unix forward slash delimiter
Use pathlib as per 

“Python 3 Quick Tip: The easy way to deal with file paths on Windows, Mac and Linux” by Adam Geitgey https://link.medium.com/Mj5HFIgOpX

(Probably should be a bug, depending on your views on Windows :)

**Comment by ivanfig** [comment]
I uninstalled the requirements, then installed them again. Now I get:

(tf_gpu) C:\Users\IvanFigueredo\Documents\python\Bitcoin-Trader-RL>./optimize.py
'.' is not recognized as an internal or external command,
operable program or batch file.

(tf_gpu) C:\Users\idf\Documents\python\Bitcoin-Trader-RL>python ./optimize.py
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./optimize.py", line 16, in <module>
    from stable_baselines.common.policies import MlpLnLstmPolicy
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\stable_baselines\__init__.py", line 1, in <module>
    from stable_baselines.a2c import A2C
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\stable_baselines\a2c\__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\stable_baselines\a2c\a2c.py", line 6, in <module>
    import tensorflow as tf
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Anaconda3\envs\tf_gpu\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(tf_gpu) C:\Users\idf\Documents\python\Bitcoin-Trader-RL>

**Comment by ivanfig** [comment]
Oops, didn't see comment above about Windows path issue. Let me see...

**Comment by stefintrim** [comment]
That latest issue is related to gpu drivers I think - you need cuda 9.0, then cudnn for cuda 9.0, then it should work ... Very finicky though, took me a while to get it all set up ... Followed this article eventually

“Installing Tensorflow with CUDA, cuDNN and GPU support on Windows 10” by Dr. Joanne Kitson https://link.medium.com/rwF7jjhPpX

That's when I ran into the path issue :)

**Comment by ivanfig** [comment]
stefintrim  I think THAT is the problem. I just tried python optimize.py and got those errors again (imp not found).

I need to spend time messing with it. I have verified that tensorflow_GPU works fine with run of the mill type programs, so it is probably with the CUDA/cuDNN drivers specific to the libraries this needs.

**Comment by TalhaAsmal** [comment]
> That latest issue is related to gpu drivers I think - you need cuda 9.0, then cudnn for cuda 9.0, then it should work ... Very finicky though, took me a while to get it all set up ... Followed this article eventually
> 
> “Installing Tensorflow with CUDA, cuDNN and GPU support on Windows 10” by Dr. Joanne Kitson https://link.medium.com/rwF7jjhPpX
> 
> That's when I ran into the path issue :)

This article is quite outdated, surprisingly. It references CUDA 9.0, which is outdated.

Follow the install guides for each piece (CUDA 10, cuDNN >=7.4.1, TensorRT 5.0, Tensorflow >=1.13), and then follow https://www.tensorflow.org/install/gpu#windows_setup for final setup (mainly ensuring all the pieces are on the PATH correctly).

If the tensorflow installation fails, try deselecting 'Visual Studio Integration' and 'NSight Compute' in the installer's advanced settings.
